language: nix

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: nix-shell --command 'make test'
    - stage: build and deploy
      script: nix-shell --command 'make build && make deploy'
